# ---------- Build stage ----------
FROM node:18-alpine AS builder

ARG NEXT_PUBLIC_ENV
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_PRINT_BRIDGE_URL
ARG NEXT_PUBLIC_PRINT_BRIDGE_KEY

ENV NEXT_PUBLIC_ENV=$NEXT_PUBLIC_ENV
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_PRINT_BRIDGE_URL=$NEXT_PUBLIC_PRINT_BRIDGE_URL
ENV NEXT_PUBLIC_PRINT_BRIDGE_KEY=$NEXT_PUBLIC_PRINT_BRIDGE_KEY

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ---------- Production stage ----------
FROM node:18-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "start"]