export const tagTypes = {
  reps: "reps",
  timelogs: "timelogs",
  stores: "stores",
  notes: "notes",
  orders: "orders",
  deliveries: "deliveries",
  products: "products",
  productLines: "productLines",
  samples: "samples",
  contacts: "contacts",
  followups: "followups",
  privateLabelOrders: "privateLabelOrders",
  privateLabelProducts: "privateLabelProducts",
};
